name: NixOS Build & Test (Gitea/Codeberg)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check Nix flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check --all-systems --show-trace

  build:
    name: Build NixOS configuration
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        host: [kernelcore]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build NixOS configuration
        run: |
          nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel \
            --show-trace \
            --print-build-logs

      - name: Check for security vulnerabilities
        run: |
          nix run nixpkgs#vulnix -- -w \
            $(nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --no-link --print-out-paths)
        continue-on-error: true

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check Nix formatting
        run: |
          nix fmt -- --check .

  security-scan:
    name: Security scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        run: |
          docker run --rm -v $(pwd):/scan aquasec/trivy:latest fs --security-checks vuln,config /scan
        continue-on-error: true
