# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gemini-cli = {
    pname = "gemini-cli";
    version = "927102ea1b9a13bdb15b30524c2db86a4dfe640e";
    src = fetchgit {
      url = "https://github.com/google-gemini/gemini-cli";
      rev = "927102ea1b9a13bdb15b30524c2db86a4dfe640e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qXxUzlLJ/rBQMaYAz5++5VQfn0e4TZ3cNkuE4Fq+V84=";
    };
    date = "2025-12-11";
  };
  lynis = {
    pname = "lynis";
    version = "3.1.6";
    src = fetchurl {
      url = "https://github.com/CISOfy/lynis/archive/3.1.6.tar.gz";
      sha256 = "sha256-KjHj4CjWufDo9QJAKtZ1KwafkIKJNRTIwCOWL1eGs7Y=";
    };
  };
  zellij = {
    pname = "zellij";
    version = "v0.43.1";
    src = fetchurl {
      url = "https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-VB2Y7+9VWCk++FrZrNKeTZILbogVE7nnclXYIHAg11o=";
    };
  };
}
