# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gemini-cli = {
    pname = "gemini-cli";
    version = "54de67536da3af801bba8ab4657769d54dd30c2a";
    src = fetchgit {
      url = "https://github.com/google-gemini/gemini-cli";
      rev = "54de67536da3af801bba8ab4657769d54dd30c2a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-53IAAiJSEK/GkUbmB1kIGiaU5bZTojG5sUBdGoEUUAc=";
    };
    date = "2025-12-11";
  };
  lynis = {
    pname = "lynis";
    version = "3.1.6";
    src = fetchurl {
      url = "https://github.com/CISOfy/lynis/archive/3.1.6.tar.gz";
      sha256 = "sha256-KjHj4CjWufDo9QJAKtZ1KwafkIKJNRTIwCOWL1eGs7Y=";
    };
  };
  zellij = {
    pname = "zellij";
    version = "v0.43.1";
    src = fetchurl {
      url = "https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz";
      sha256 = "sha256-VB2Y7+9VWCk++FrZrNKeTZILbogVE7nnclXYIHAg11o=";
    };
  };
}
